import classes from "./table.module.css";
import TableGroup from "./tableGroup";

const Table = () => {
  return (
    <div className={classes.mainContainer}>
      <TableGroup
        groupTitleBackground="linear-gradient(45deg,red,blue)"
        groupTitleText="GROUP 1"
        itemBackground1="linear-gradient(45deg,red,blue)"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemBackground2="linear-gradient(45deg,red,blue)"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemBackground3="linear-gradient(45deg,red,blue)"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemBackground4="linear-gradient(45deg,red,blue)"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />
            <TableGroup
        groupTitleBackground="linear-gradient(45deg,red,blue)"
        groupTitleText="GROUP 2"
        itemBackground1="linear-gradient(45deg,red,blue)"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemBackground2="linear-gradient(45deg,red,blue)"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemBackground3="linear-gradient(45deg,red,blue)"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemBackground4="linear-gradient(45deg,red,blue)"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />
            <TableGroup
        groupTitleBackground="linear-gradient(45deg,red,blue)"
        groupTitleText="GROUP 3"
        itemBackground1="linear-gradient(45deg,red,blue)"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemBackground2="linear-gradient(45deg,red,blue)"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemBackground3="linear-gradient(45deg,red,blue)"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemBackground4="linear-gradient(45deg,red,blue)"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />
            <TableGroup
        groupTitleBackground="linear-gradient(45deg,red,blue)"
        groupTitleText="GROUP 4"
        itemBackground1="linear-gradient(45deg,red,blue)"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemBackground2="linear-gradient(45deg,red,blue)"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemBackground3="linear-gradient(45deg,red,blue)"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemBackground4="linear-gradient(45deg,red,blue)"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />
            <TableGroup
        groupTitleBackground="linear-gradient(45deg,red,blue)"
        groupTitleText="GROUP 5"
        itemBackground1="linear-gradient(45deg,red,blue)"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemBackground2="linear-gradient(45deg,red,blue)"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemBackground3="linear-gradient(45deg,red,blue)"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemBackground4="linear-gradient(45deg,red,blue)"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />
            <TableGroup
        groupTitleBackground="linear-gradient(45deg,red,blue)"
        groupTitleText="GROUP 6"
        itemBackground1="linear-gradient(45deg,red,blue)"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemBackground2="linear-gradient(45deg,red,blue)"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemBackground3="linear-gradient(45deg,red,blue)"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemBackground4="linear-gradient(45deg,red,blue)"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />
            <TableGroup
        groupTitleBackground="linear-gradient(45deg,red,blue)"
        groupTitleText="GROUP 7"
        itemBackground1="linear-gradient(45deg,red,blue)"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemBackground2="linear-gradient(45deg,red,blue)"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemBackground3="linear-gradient(45deg,red,blue)"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemBackground4="linear-gradient(45deg,red,blue)"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />
            <TableGroup
        groupTitleBackground="linear-gradient(45deg,red,blue)"
        groupTitleText="GROUP 8"
        itemBackground1="linear-gradient(45deg,red,blue)"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemBackground2="linear-gradient(45deg,red,blue)"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemBackground3="linear-gradient(45deg,red,blue)"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemBackground4="linear-gradient(45deg,red,blue)"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />
            <TableGroup
        groupTitleBackground="linear-gradient(45deg,red,blue)"
        groupTitleText="GROUP 9"
        itemBackground1="linear-gradient(45deg,red,blue)"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemBackground2="linear-gradient(45deg,red,blue)"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemBackground3="linear-gradient(45deg,red,blue)"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemBackground4="linear-gradient(45deg,red,blue)"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />
            <TableGroup
        groupTitleBackground="linear-gradient(45deg,red,blue)"
        groupTitleText="GROUP 10"
        itemBackground1="linear-gradient(45deg,red,blue)"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemBackground2="linear-gradient(45deg,red,blue)"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemBackground3="linear-gradient(45deg,red,blue)"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemBackground4="linear-gradient(45deg,red,blue)"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />
    </div>
  );
};

export default Table;
