import classes from "./table.module.css";
import TableItem from "./tableItem";

const Table = () => {
  return (
    <div className={classes.mainContainer}>
      <TableItem
        mainTitle="GROUP 1"
        mainTitleBackgroundColor="pink"
        item1BackgroundColor="yellow"
        item2BackgroundColor="blue"
        item3BackgroundColor="green"
        item4BackgroundColor="red"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />

      <TableItem
        mainTitle="GROUP 2"
        mainTitleBackgroundColor="pink"
        item1BackgroundColor="yellow"
        item2BackgroundColor="blue"
        item3BackgroundColor="green"
        item4BackgroundColor="red"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />

      <TableItem
        mainTitle="GROUP 3"
        mainTitleBackgroundColor="pink"
        item1BackgroundColor="yellow"
        item2BackgroundColor="blue"
        item3BackgroundColor="green"
        item4BackgroundColor="red"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />

      <TableItem
        mainTitle="GROUP 4"
        mainTitleBackgroundColor="pink"
        item1BackgroundColor="yellow"
        item2BackgroundColor="blue"
        item3BackgroundColor="green"
        item4BackgroundColor="red"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />

      <TableItem
        mainTitle="GROUP 5"
        mainTitleBackgroundColor="pink"
        item1BackgroundColor="yellow"
        item2BackgroundColor="blue"
        item3BackgroundColor="green"
        item4BackgroundColor="red"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />

      <TableItem
        mainTitle="GROUP 6"
        mainTitleBackgroundColor="pink"
        item1BackgroundColor="yellow"
        item2BackgroundColor="blue"
        item3BackgroundColor="green"
        item4BackgroundColor="red"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />

      <TableItem
        mainTitle="GROUP 7"
        mainTitleBackgroundColor="pink"
        item1BackgroundColor="yellow"
        item2BackgroundColor="blue"
        item3BackgroundColor="green"
        item4BackgroundColor="red"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />

      <TableItem
        mainTitle="GROUP 8"
        mainTitleBackgroundColor="pink"
        item1BackgroundColor="yellow"
        item2BackgroundColor="blue"
        item3BackgroundColor="green"
        item4BackgroundColor="red"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />

      <TableItem
        mainTitle="GROUP 9"
        mainTitleBackgroundColor="pink"
        item1BackgroundColor="yellow"
        item2BackgroundColor="blue"
        item3BackgroundColor="green"
        item4BackgroundColor="red"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />

      <TableItem
        mainTitle="GROUP 10"
        mainTitleBackgroundColor="pink"
        item1BackgroundColor="yellow"
        item2BackgroundColor="blue"
        item3BackgroundColor="green"
        item4BackgroundColor="red"
        itemsTitle1="TITLE 1"
        itemsText1="TEXT 1"
        itemsSubText1="SUBTEXT 1"
        itemsTitle2="TITLE 2"
        itemsText2="TEXT 2"
        itemsSubText2="SUBTEXT 2"
        itemsTitle3="TITLE 3"
        itemsText3="TEXT 3"
        itemsSubText3="SUBTEXT 3"
        itemsTitle4="TITLE 4"
        itemsText4="TEXT 4"
        itemsSubText4="SUBTEXT 4"
      />
    </div>
  );
};

export default Table;
